"""empty message

Revision ID: ad266b618d9c
Revises: 
Create Date: 2020-01-15 20:17:34.873774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad266b618d9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('liters')
    op.drop_table('entries')
    op.add_column('pods', sa.Column('seq_butt', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pods', 'seq_butt')
    op.create_table('entries',
    sa.Column('entry_id', sa.INTEGER(), nullable=False),
    sa.Column('ep_num', sa.VARCHAR(length=60), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('l_date', sa.DATETIME(), nullable=True),
    sa.Column('pod_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.pod_id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_table('liters',
    sa.Column('liter_id', sa.INTEGER(), nullable=False),
    sa.Column('drink_date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('liter_id')
    )
    # ### end Alembic commands ###
